VanStoreBE/Models/ProDetail.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VanStoreBE.Models
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;
    public partial class ProDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProDetail()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
        [Required(ErrorMessage = "Bạn chưa nhập tên danh mục này !!!")]      
        public int ProDeID { get; set; }
        [Required(ErrorMessage = "Bạn chưa nhập tên danh mục này !!!")]
        public int ProID { get; set; }
        [Required(ErrorMessage = "Bạn chưa nhập tên danh mục này !!!")]
        public int SupID { get; set; }
        [Required(ErrorMessage = "Bạn chưa nhập tên danh mục này !!!")]
        public int ColorID { get; set; }
        [Required(ErrorMessage = "Bạn chưa nhập tên danh mục này !!!")]
        public double Price { get; set; }
        [Required(ErrorMessage = "Bạn chưa nhập tên danh mục này !!!")]
        public int RemainQuantity { get; set; }
        public Nullable<int> SoldQuantity { get; set; }
        public Nullable<int> ViewQuantity { get; set; }
        public Nullable<int> DISCOUNT { get; set; }
        [Required(ErrorMessage = "Bạn chưa nhập tên danh mục này !!!")]
        public int SIZE { get; set; }
        [Required(ErrorMessage = "Bạn chưa nhập tên danh mục này !!!")]
        [StringLength(5, ErrorMessage = "Số kí tự không được vượt quá 5")]
        public string SHAPE { get; set; }
        public string KEYWORD { get; set; }
        public string Image1 { get; set; }
        public string Image2 { get; set; }
        public string Image3 { get; set; }
        public string Image4 { get; set; }
        public string Image5 { get; set; }

        public virtual Color Color { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual Product Product { get; set; }
        public virtual Size Size1 { get; set; }
        public virtual Supplier Supplier { get; set; }
        [NotMapped]
        public HttpPostedFileBase UploadImg1 { get; set; }
        [NotMapped]
        public HttpPostedFileBase UploadImg2 { get; set; }
        [NotMapped]
        public HttpPostedFileBase UploadImg3 { get; set; }
        [NotMapped]
        public HttpPostedFileBase UploadImg4 { get; set; }
        [NotMapped]
        public HttpPostedFileBase UploadImg5 { get; set; }
    }
}

VanStoreBE/Controllers/ProDetailsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using VanStoreBE.Models;
using System.IO;

namespace VanStoreBE.Controllers
{
    public class ProDetailsController : Controller
    {
        private VanStoreEntities db = new VanStoreEntities();

        // GET: ProDetails
        public ActionResult Index()
        {
            var proDetails = db.ProDetails.Include(p => p.Color).Include(p => p.Product).Include(p => p.Supplier).Include(p => p.Size1);
            return View(proDetails.ToList());
        }

        // GET: ProDetails/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProDetail proDetail = db.ProDetails.Find(id);
            if (proDetail == null)
            {
                return HttpNotFound();
            }
            return View(proDetail);
        }

        // GET: ProDetails/Create
        public ActionResult Create()
        {
            ViewBag.ColorID = new SelectList(db.Colors, "ColorID", "ColorName");
            ViewBag.ProID = new SelectList(db.Products, "ProID", "ProName");
            ViewBag.SupID = new SelectList(db.Suppliers, "SupID", "SupName");
            ViewBag.SIZE = new SelectList(db.Sizes, "SizeID", "SizeNum");
            return View();
        }

        // POST: ProDetails/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProDeID,ProID,SupID,ColorID,Price,RemainQuantity,SoldQuantity,ViewQuantity,DISCOUNT,SIZE,SHAPE,KEYWORD,Image1,Image2,Image3,Image4,Image5," + "UploadImg1,UploadImg2,UploadImg3,UploadImg4,UploadImg5")] ProDetail proDetail)
        {
            if (ModelState.IsValid)
            {
                // Kiểm tra RemainQuantity, SoldQuantity, và ViewQuantity không âm
                if (proDetail.RemainQuantity < 0 || proDetail.SoldQuantity < 0 || proDetail.ViewQuantity < 0)
                {
                    ModelState.AddModelError("", "Số lượng không được < 0!");
                    // Thực hiện các hành động xử lý lỗi khác nếu cần
                }
                if (proDetail.UploadImg1 == null || proDetail.UploadImg2 == null || proDetail.UploadImg3 == null || proDetail.UploadImg4 == null || proDetail.UploadImg5 == null)
                {
                    ViewBag.error = "Please select a image!!";
                }
                else
                {
                    if (proDetail.UploadImg1 != null)
                    {
                        string path = "~/Content/images/";
                        string filename = Path.GetFileName(proDetail.UploadImg1.FileName);
                        proDetail.Image1 = path + filename;
                        proDetail.UploadImg1.SaveAs(Path.Combine(Server.MapPath(path), filename));
                    }
                    if (proDetail.UploadImg2 != null)
                    {
                        string path = "~/Content/images/";
                        string filename = Path.GetFileName(proDetail.UploadImg2.FileName);
                        proDetail.Image2 = path + filename;
                        proDetail.UploadImg2.SaveAs(Path.Combine(Server.MapPath(path), filename));
                    }
                    if (proDetail.UploadImg3 != null)
                    {
                        string path = "~/Content/images/";
                        string filename = Path.GetFileName(proDetail.UploadImg3.FileName);
                        proDetail.Image3 = path + filename;
                        proDetail.UploadImg3.SaveAs(Path.Combine(Server.MapPath(path), filename));
                    }
                    if (proDetail.UploadImg4 != null)
                    {
                        string path = "~/Content/images/";
                        string filename = Path.GetFileName(proDetail.UploadImg4.FileName);
                        proDetail.Image4 = path + filename;
                        proDetail.UploadImg4.SaveAs(Path.Combine(Server.MapPath(path), filename));
                    }
                    if (proDetail.UploadImg5 != null)
                    {
                        string path = "~/Content/images/";
                        string filename = Path.GetFileName(proDetail.UploadImg5.FileName);
                        proDetail.Image5 = path + filename;
                        proDetail.UploadImg5.SaveAs(Path.Combine(Server.MapPath(path), filename));
                    }
                    db.ProDetails.Add(proDetail);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }

            ViewBag.ColorID = new SelectList(db.Colors, "ColorID", "ColorName", proDetail.ColorID);
            ViewBag.ProID = new SelectList(db.Products, "ProID", "ProName", proDetail.ProID);
            ViewBag.SupID = new SelectList(db.Suppliers, "SupID", "SupName", proDetail.SupID);
            ViewBag.SIZE = new SelectList(db.Sizes, "SizeID", "SizeNum", proDetail.SIZE);
            return View(proDetail);
        }

        // GET: ProDetails/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProDetail proDetail = db.ProDetails.Find(id);
            if (proDetail == null)
            {
                return HttpNotFound();
            }
            ViewBag.ColorID = new SelectList(db.Colors, "ColorID", "ColorName", proDetail.ColorID);
            ViewBag.ProID = new SelectList(db.Products, "ProID", "ProName", proDetail.ProID);
            ViewBag.SupID = new SelectList(db.Suppliers, "SupID", "SupName", proDetail.SupID);
            ViewBag.SIZE = new SelectList(db.Sizes, "SizeID", "SizeNum", proDetail.SIZE);
            return View(proDetail);
        }

        // POST: ProDetails/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProDeID,ProID,SupID,ColorID,Price,RemainQuantity,SoldQuantity,ViewQuantity,DISCOUNT,SIZE,SHAPE,KEYWORD,Image1,Image2,Image3,Image4,Image5," + "UploadImg1,UploadImg2,UploadImg3,UploadImg4,UploadImg5")] ProDetail proDetail)
        {
            if (ModelState.IsValid)
            {
                if (proDetail.UploadImg1 == null || proDetail.UploadImg2 == null || proDetail.UploadImg3 == null || proDetail.UploadImg4 == null || proDetail.UploadImg5 == null)
                {
                    ViewBag.error = "Please select a image!!";
                }
                else
                {
                    if (proDetail.UploadImg1 != null)
                    {
                        string path = "~/Content/images/";
                        string filename = Path.GetFileName(proDetail.UploadImg1.FileName);
                        proDetail.Image1 = path + filename;
                        proDetail.UploadImg1.SaveAs(Path.Combine(Server.MapPath(path), filename));
                    }
                    if (proDetail.UploadImg2 != null)
                    {
                        string path = "~/Content/images/";
                        string filename = Path.GetFileName(proDetail.UploadImg2.FileName);
                        proDetail.Image2 = path + filename;
                        proDetail.UploadImg2.SaveAs(Path.Combine(Server.MapPath(path), filename));
                    }
                    if (proDetail.UploadImg3 != null)
                    {
                        string path = "~/Content/images/";
                        string filename = Path.GetFileName(proDetail.UploadImg3.FileName);
                        proDetail.Image3 = path + filename;
                        proDetail.UploadImg3.SaveAs(Path.Combine(Server.MapPath(path), filename));
                    }
                    if (proDetail.UploadImg4 != null)
                    {
                        string path = "~/Content/images/";
                        string filename = Path.GetFileName(proDetail.UploadImg4.FileName);
                        proDetail.Image4 = path + filename;
                        proDetail.UploadImg4.SaveAs(Path.Combine(Server.MapPath(path), filename));
                    }
                    if (proDetail.UploadImg5 != null)
                    {
                        string path = "~/Content/images/";
                        string filename = Path.GetFileName(proDetail.UploadImg5.FileName);
                        proDetail.Image5 = path + filename;
                        proDetail.UploadImg5.SaveAs(Path.Combine(Server.MapPath(path), filename));
                    }
                    db.Entry(proDetail).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            ViewBag.ColorID = new SelectList(db.Colors, "ColorID", "ColorName", proDetail.ColorID);
            ViewBag.ProID = new SelectList(db.Products, "ProID", "ProName", proDetail.ProID);
            ViewBag.SupID = new SelectList(db.Suppliers, "SupID", "SupName", proDetail.SupID);
            ViewBag.SIZE = new SelectList(db.Sizes, "SizeID", "SizeNum", proDetail.SIZE);
            return View(proDetail);
        }

        // GET: ProDetails/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {

VanStoreBE/Views/ProDetails/Create.cshtml
@model VanStoreBE.Models.ProDetail

@{
    ViewBag.Title = "Create";
}

@{
    ViewBag.Title = "Create";
}

<h1>QUẢN LÝ HÀNG HÓA</h1>

@using (Html.BeginForm("Create", "ProDetails", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <div class="control-label col-md-2">Tên hàng hóa</div>
            <div class="col-md-10">
                @Html.DropDownList("ProID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">Tên nhà cung cấp</div>
            <div class="col-md-10">
                @Html.DropDownList("SupID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SupID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">Màu sắc</div>
            <div class="col-md-10">
                @Html.DropDownList("ColorID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ColorID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">Giá</div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control", @type = "number" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">Số lượng tồn</div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.RemainQuantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RemainQuantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">Số lượng đã bán</div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoldQuantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoldQuantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">Xem số lượng</div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.ViewQuantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ViewQuantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">Giảm giá</div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.DISCOUNT, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DISCOUNT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">Kích cỡ</div>
            <div class="col-md-10">
                @Html.DropDownList("SIZE", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Size1.SizeNum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">Dáng giày</div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.SHAPE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SHAPE, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                <div class="control-label col-md-2">Từ khóa</div>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.KEYWORD, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.KEYWORD, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            <div class="control-label col-md-2">Hình 1</div>
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.UploadImg1, htmlAttributes: new { @type = "file" })
                @Html.ValidationMessageFor(model => model.UploadImg1, "", new { @class = "text-danger" })
                <div style="color:red">
                    @ViewBag.error
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">Hình 2</div>
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.UploadImg2, htmlAttributes: new { @type = "file" })
                @Html.ValidationMessageFor(model => model.UploadImg2, "", new { @class = "text-danger" })
                <div style="color:red">
                    @ViewBag.error
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">Hình 3</div>
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.UploadImg3, htmlAttributes: new { @type = "file" })
                @Html.ValidationMessageFor(model => model.UploadImg3, "", new { @class = "text-danger" })
                <div style="color:red">
                    @ViewBag.error
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">Hình 4</div>
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.UploadImg4, htmlAttributes: new { @type = "file" })
                @Html.ValidationMessageFor(model => model.UploadImg4, "", new { @class = "text-danger" })
                <div style="color:red">
                    @ViewBag.error
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">Hình 5</div>
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.UploadImg5, htmlAttributes: new { @type = "file" })
                @Html.ValidationMessageFor(model => model.UploadImg5, "", new { @class = "text-danger" })
                <div style="color:red">
                    @ViewBag.error
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm mới" class="btn btn-success" />
                @Html.ActionLink("Quay lại", "Index", null, new { @class = "btn btn-primary" })
            </div>
        </div>
    </div>
}

VanStoreBE/Views/ProDetails/Delete.cshtml
@model VanStoreBE.Models.ProDetail

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ProDetail</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RemainQuantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RemainQuantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoldQuantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoldQuantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ViewQuantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ViewQuantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DISCOUNT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DISCOUNT)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SHAPE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SHAPE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.KEYWORD)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KEYWORD)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image3)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image3)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image4)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image4)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image5)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image5)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Color.ColorName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Color.ColorName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Product.ProName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product.ProName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Size1.SizeNum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Size1.SizeNum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Supplier.SupName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Supplier.SupName)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

VanStoreBE/Views/ProDetails/Details.cshtml
@model VanStoreBE.Models.ProDetail

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>ProDetail</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RemainQuantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RemainQuantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoldQuantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoldQuantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ViewQuantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ViewQuantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DISCOUNT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DISCOUNT)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SHAPE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SHAPE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.KEYWORD)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KEYWORD)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image3)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image3)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image4)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image4)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image5)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image5)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Color.ColorName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Color.ColorName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Product.ProName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product.ProName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Size1.SizeNum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Size1.SizeNum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Supplier.SupName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Supplier.SupName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ProDeID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

VanStoreBE/Views/ProDetails/Index.cshtml
@model IEnumerable<VanStoreBE.Models.ProDetail>

@{
    ViewBag.Title = "Index";
}
<style>
    th {
        white-space: nowrap;
    }
</style>
<h1>QUẢN LÝ HÀNG HÓA</h1>

<p>
    @Html.ActionLink("Thêm mới", "Create", null, new { @class = "btn btn-success" })
</p>
<table class="table" style="text-align:center; border: 1px solid black; vertical-align: middle;">
    <tr>
        <th>
            Tên sản phẩm
        </th>
        <th>
            Nhà cung cấp
        </th>
        <th>
            Giá
        </th>
        <th>
            Màu sắc
        </th>
        <th>
            Xem số lượng còn lại
        </th>
        <th>
            Xem số lượng
        </th>

        <th>
            Xem số lượng đã bán
        </th>
        <th>
            Cỡ giày
        </th>
        <th>
            Dáng giày
        </th>
        <th>
            Giảm giá
        </th>
        <th>
            Ảnh 1
        </th>
        <th>
            Ảnh 2
        </th>
        <th>
            Ảnh 3
        </th>
        <th>
            Ảnh 4
        </th>
        <th>
            Ảnh 5
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Product.ProName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Supplier.SupName)
            </td>
            <td>
                @string.Format("{0:N0}", item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Color.ColorName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ViewQuantity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RemainQuantity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SoldQuantity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Size1.SizeNum)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SHAPE)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.DISCOUNT)
            </td>
            <td>
                <img src="@Url.Content(item.Image1)" width="50" height="50" />
            </td>
            <td>
                <img src="@Url.Content(item.Image2)" width="50" height="50" />
            </td>
            <td>
                <img src="@Url.Content(item.Image3)" width="50" height="50" />
            </td>
            <td>
                <img src="@Url.Content(item.Image4)" width="50" height="50" />
            </td>
            <td>
                <img src="@Url.Content(item.Image5)" width="50" height="50" />
            </td>

            <td>
                @Html.ActionLink("Sửa", "Edit", new { id = item.ProDeID }, new { @class = "btn btn-primary" })
                @Html.ActionLink("Xóa", "Delete", new { id = item.ProDeID }, new { @class = "btn btn-danger" })
            </td>
        </tr>
    }

</table>